import type { Component } from "svelte";

type AnyComponent = Component<Record<string, unknown>>;

export const Accordion: AnyComponent;
export const AccordionContent: AnyComponent;
export const AccordionHeader: AnyComponent;
export const AccordionItem: AnyComponent;
export const AccordionTrigger: AnyComponent;
export const Alert: AnyComponent;
export const AlertAction: AnyComponent;
export const AlertDescription: AnyComponent;
export const AlertDialog: AnyComponent;
export const AlertDialogAction: AnyComponent;
export const AlertDialogCancel: AnyComponent;
export const AlertDialogDescription: AnyComponent;
export const AlertDialogFooter: AnyComponent;
export const AlertDialogHeader: AnyComponent;
export const AlertDialogPopup: AnyComponent;
export const AlertDialogTitle: AnyComponent;
export const AlertDialogTrigger: AnyComponent;
export const AlertTitle: AnyComponent;
export const Autocomplete: AnyComponent;
export const AutocompleteCollection: AnyComponent;
export const AutocompleteEmpty: AnyComponent;
export const AutocompleteGroup: AnyComponent;
export const AutocompleteGroupLabel: AnyComponent;
export const AutocompleteInput: AnyComponent;
export const AutocompleteItem: AnyComponent;
export const AutocompleteList: AnyComponent;
export const AutocompletePopup: AnyComponent;
export const AutocompleteSeparator: AnyComponent;
export const AutocompleteStatus: AnyComponent;
export const Avatar: AnyComponent;
export const AvatarFallback: AnyComponent;
export const AvatarImage: AnyComponent;
export const Badge: AnyComponent;
export const Breadcrumb: AnyComponent;
export const Button: AnyComponent;
export const Calendar: AnyComponent;
export const Card: AnyComponent;
export const CardDescription: AnyComponent;
export const CardFooter: AnyComponent;
export const CardHeader: AnyComponent;
export const CardPanel: AnyComponent;
export const CardTitle: AnyComponent;
export const Checkbox: AnyComponent;
export const CheckboxGroup: AnyComponent;
export const Collapsible: AnyComponent;
export const CollapsibleContent: AnyComponent;
export const CollapsibleTrigger: AnyComponent;
export const Combobox: AnyComponent;
export const ComboboxClear: AnyComponent;
export const ComboboxCollection: AnyComponent;
export const ComboboxEmpty: AnyComponent;
export const ComboboxGroup: AnyComponent;
export const ComboboxGroupLabel: AnyComponent;
export const ComboboxInput: AnyComponent;
export const ComboboxItem: AnyComponent;
export const ComboboxList: AnyComponent;
export const ComboboxPopup: AnyComponent;
export const ComboboxSeparator: AnyComponent;
export const ComboboxTrigger: AnyComponent;
export const ComboboxValue: AnyComponent;
export const Command: AnyComponent;
export const CommandCollection: AnyComponent;
export const CommandDialog: AnyComponent;
export const CommandDialogPopup: AnyComponent;
export const CommandDialogTrigger: AnyComponent;
export const CommandEmpty: AnyComponent;
export const CommandFooter: AnyComponent;
export const CommandGroup: AnyComponent;
export const CommandGroupLabel: AnyComponent;
export const CommandInput: AnyComponent;
export const CommandItem: AnyComponent;
export const CommandList: AnyComponent;
export const CommandPanel: AnyComponent;
export const CommandSeparator: AnyComponent;
export const CommandShortcut: AnyComponent;
export const DatePicker: AnyComponent;
export const Dialog: AnyComponent;
export const DialogClose: AnyComponent;
export const DialogDescription: AnyComponent;
export const DialogFooter: AnyComponent;
export const DialogHeader: AnyComponent;
export const DialogPanel: AnyComponent;
export const DialogPopup: AnyComponent;
export const DialogTitle: AnyComponent;
export const DialogTrigger: AnyComponent;
export const Drawer: AnyComponent;
export const DrawerClose: AnyComponent;
export const DrawerContent: AnyComponent;
export const DrawerCreateHandle: AnyComponent;
export const DrawerDescription: AnyComponent;
export const DrawerFooter: AnyComponent;
export const DrawerHeader: AnyComponent;
export const DrawerPanel: AnyComponent;
export const DrawerPopup: AnyComponent;
export const DrawerTitle: AnyComponent;
export const DrawerTrigger: AnyComponent;
export const Empty: AnyComponent;
export const EmptyContent: AnyComponent;
export const EmptyDescription: AnyComponent;
export const EmptyHeader: AnyComponent;
export const EmptyMedia: AnyComponent;
export const EmptyTitle: AnyComponent;
export const Field: AnyComponent;
export const FieldDescription: AnyComponent;
export const FieldError: AnyComponent;
export const FieldLabel: AnyComponent;
export const Fieldset: AnyComponent;
export const FieldsetLegend: AnyComponent;
export const FieldValidity: AnyComponent;
export const Form: AnyComponent;
export const Frame: AnyComponent;
export const FrameDescription: AnyComponent;
export const FrameFooter: AnyComponent;
export const FrameHeader: AnyComponent;
export const FramePanel: AnyComponent;
export const FrameTitle: AnyComponent;
export const Group: AnyComponent;
export const GroupSeparator: AnyComponent;
export const Input: AnyComponent;
export const InputGroup: AnyComponent;
export const InputGroupAddon: AnyComponent;
export const InputGroupInput: AnyComponent;
export const InputGroupText: AnyComponent;
export const InputGroupTextarea: AnyComponent;
export const Kbd: AnyComponent;
export const Label: AnyComponent;
export const Menu: AnyComponent;
export const MenuCheckboxItem: AnyComponent;
export const MenuGroup: AnyComponent;
export const MenuGroupLabel: AnyComponent;
export const MenuItem: AnyComponent;
export const MenuPopup: AnyComponent;
export const MenuRadioGroup: AnyComponent;
export const MenuRadioItem: AnyComponent;
export const MenuSeparator: AnyComponent;
export const MenuShortcut: AnyComponent;
export const MenuSub: AnyComponent;
export const MenuSubPopup: AnyComponent;
export const MenuSubTrigger: AnyComponent;
export const MenuTrigger: AnyComponent;
export const Meter: AnyComponent;
export const MeterIndicator: AnyComponent;
export const MeterLabel: AnyComponent;
export const MeterTrack: AnyComponent;
export const MeterValue: AnyComponent;
export const OTPField: AnyComponent;
export const OTPFieldCell: AnyComponent;
export const OTPFieldInput: AnyComponent;
export const Pagination: AnyComponent;
export const PaginationContent: AnyComponent;
export const PaginationEllipsis: AnyComponent;
export const PaginationItem: AnyComponent;
export const PaginationLink: AnyComponent;
export const PaginationNext: AnyComponent;
export const PaginationNextButton: AnyComponent;
export const PaginationPage: AnyComponent;
export const PaginationPrevious: AnyComponent;
export const PaginationPrevButton: AnyComponent;
export const Popover: AnyComponent;
export const PopoverClose: AnyComponent;
export const PopoverDescription: AnyComponent;
export const PopoverPopup: AnyComponent;
export const PopoverTitle: AnyComponent;
export const PopoverTrigger: AnyComponent;
export const PreviewCard: AnyComponent;
export const PreviewCardPopup: AnyComponent;
export const PreviewCardTrigger: AnyComponent;
export const Progress: AnyComponent;
export const RadioGroup: AnyComponent;
export const RadioGroupItem: AnyComponent;
export const ScrollArea: AnyComponent;
export const ScrollAreaCorner: AnyComponent;
export const ScrollAreaScrollbar: AnyComponent;
export const ScrollAreaThumb: AnyComponent;
export const ScrollAreaViewport: AnyComponent;
export const Select: AnyComponent;
export const SelectGroup: AnyComponent;
export const SelectGroupLabel: AnyComponent;
export const SelectItem: AnyComponent;
export const SelectPopup: AnyComponent;
export const SelectScrollDownButton: AnyComponent;
export const SelectScrollUpButton: AnyComponent;
export const SelectTrigger: AnyComponent;
export const SelectValue: AnyComponent;
export const SelectViewport: AnyComponent;
export const Separator: AnyComponent;
export const Sheet: AnyComponent;
export const SheetClose: AnyComponent;
export const SheetContent: AnyComponent;
export const SheetDescription: AnyComponent;
export const SheetFooter: AnyComponent;
export const SheetHeader: AnyComponent;
export const SheetPanel: AnyComponent;
export const SheetPopup: AnyComponent;
export const SheetTitle: AnyComponent;
export const SheetTrigger: AnyComponent;
export const Sidebar: AnyComponent;
export const SidebarContent: AnyComponent;
export const SidebarFooter: AnyComponent;
export const SidebarGroup: AnyComponent;
export const SidebarGroupAction: AnyComponent;
export const SidebarGroupContent: AnyComponent;
export const SidebarGroupLabel: AnyComponent;
export const SidebarHeader: AnyComponent;
export const SidebarInput: AnyComponent;
export const SidebarInset: AnyComponent;
export const SidebarMenu: AnyComponent;
export const SidebarMenuAction: AnyComponent;
export const SidebarMenuBadge: AnyComponent;
export const SidebarMenuButton: AnyComponent;
export const SidebarMenuItem: AnyComponent;
export const SidebarMenuSkeleton: AnyComponent;
export const SidebarMenuSub: AnyComponent;
export const SidebarMenuSubButton: AnyComponent;
export const SidebarMenuSubItem: AnyComponent;
export const SidebarProvider: AnyComponent;
export const SidebarRail: AnyComponent;
export const SidebarSeparator: AnyComponent;
export const SidebarTrigger: AnyComponent;
export const Skeleton: AnyComponent;
export const Slider: AnyComponent;
export const SliderRange: AnyComponent;
export const SliderThumb: AnyComponent;
export const SliderThumbLabel: AnyComponent;
export const SliderTick: AnyComponent;
export const SliderTickLabel: AnyComponent;
export const Spinner: AnyComponent;
export const Switch: AnyComponent;
export const SwitchThumb: AnyComponent;
export const Table: AnyComponent;
export const TableBody: AnyComponent;
export const TableCaption: AnyComponent;
export const TableCell: AnyComponent;
export const TableFooter: AnyComponent;
export const TableHead: AnyComponent;
export const TableHeader: AnyComponent;
export const TableRow: AnyComponent;
export const Tabs: AnyComponent;
export const TabsContent: AnyComponent;
export const TabsList: AnyComponent;
export const TabsTrigger: AnyComponent;
export const Textarea: AnyComponent;
export const Toast: AnyComponent;
export const Toggle: AnyComponent;
export const ToggleGroup: AnyComponent;
export const ToggleGroupItem: AnyComponent;
export const Toolbar: AnyComponent;
export const ToolbarButton: AnyComponent;
export const ToolbarGroup: AnyComponent;
export const ToolbarGroupItem: AnyComponent;
export const ToolbarLink: AnyComponent;
export const ToolbarSeparator: AnyComponent;
export const Tooltip: AnyComponent;
export const TooltipPopup: AnyComponent;
export const TooltipProvider: AnyComponent;
export const TooltipTrigger: AnyComponent;

export type ComponentStatus = "stable" | "experimental" | "deferred";
export type ComponentFoundation = "bits" | "native" | "compound" | "custom";
export type ParticlePriority = "mvp" | "later" | "unsupported";
export type ComponentMetadata = {
	category: string;
	description: string;
	docsUrl: string;
	firstImplementationPass: string;
	foundation: ComponentFoundation;
	hasLocalPrimitiveRef: boolean;
	name: string;
	particlePriority: ParticlePriority;
	particles: number;
	parts: string[];
	primitive: string;
	slug: string;
	status: ComponentStatus;
	tier: string;
	title: string;
};

export const stableComponents: string[];
export const experimentalComponents: string[];
export const deferredComponents: string[];
export const componentParts: Record<string, string[]>;
export const componentStatus: Record<string, ComponentStatus>;
export const componentMetadata: Record<string, ComponentMetadata>;
export function cn(...inputs: unknown[]): string;
