/**
 * Root components accept composed children first and only render their
 * convenience props when no children snippet is supplied.
 */
export const compositionModel = Object.freeze({
	root: "children-first-convenience",
	childrenPrecedence: "custom-children",
	fallback: "explicit-props",
});

/**
 * The authoritative root-composition contract. Unlike the legacy default
 * above, this map records deliberate exceptions and must stay in exact
 * lockstep with componentMetadata.
 */
export const componentComposition = Object.freeze({
	Accordion: "children-first-fallback",
	Alert: "presentational",
	AlertDialog: "children-first-fallback",
	Autocomplete: "children-first-fallback",
	Avatar: "children-first-fallback",
	Badge: "presentational",
	Breadcrumb: "presentational",
	Button: "presentational",
	Calendar: "payload-snippet",
	Card: "presentational",
	Checkbox: "presentational",
	CheckboxGroup: "content-children",
	Collapsible: "content-children",
	Combobox: "children-first-fallback",
	Command: "children-first-fallback",
	DatePicker: "children-first-fallback",
	Dialog: "children-first-fallback",
	Empty: "presentational",
	Field: "content-children",
	Fieldset: "content-children",
	Form: "presentational",
	Frame: "presentational",
	Group: "presentational",
	Input: "presentational",
	InputGroup: "presentational",
	Kbd: "presentational",
	Label: "presentational",
	Menu: "children-first-fallback",
	ContextMenu: "compound",
	Meter: "content-children",
	OTPField: "payload-snippet",
	Pagination: "payload-snippet",
	Popover: "children-first-fallback",
	PreviewCard: "children-first-fallback",
	Progress: "content-children",
	RadioGroup: "children-first-fallback",
	ScrollArea: "presentational",
	Select: "children-first-fallback",
	Separator: "presentational",
	Sheet: "children-first-fallback",
	Skeleton: "presentational",
	Slider: "payload-snippet",
	Spinner: "presentational",
	Switch: "content-children",
	Table: "presentational",
	Tabs: "children-first-fallback",
	Textarea: "presentational",
	Toggle: "presentational",
	ToggleGroup: "children-first-fallback",
	Toolbar: "presentational",
	Tooltip: "children-first-fallback",
	Drawer: "children-first-fallback",
	Sidebar: "additive",
	Toast: "content-children",
	NumberField: "children-first-fallback",
});

export const componentMetadata = Object.freeze({
	Accordion: {
		category: "Layout & Navigation",
		description: "A set of collapsible panels with headings and content.",
		hasLocalPrimitiveRef: true,
		name: "Accordion",
		particles: 4,
		slug: "accordion",
		title: "Accordion",
		firstImplementationPass:
			"Wrap Bits UI Accordion parts with COSS-compatible item, trigger, and content styling; preserve array-style value handling and collapsible examples.",
		primitive: "Accordion",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["AccordionContent", "AccordionHeader", "AccordionItem", "AccordionTrigger"],
		particlePriority: "mvp",
		status: "stable",
	},
	Alert: {
		category: "Feedback & Status",
		description: "A callout for displaying important information.",
		hasLocalPrimitiveRef: true,
		name: "Alert",
		particles: 7,
		slug: "alert",
		title: "Alert",
		firstImplementationPass:
			"Implement as styled region/callout primitives with variant classes, icon slot support, title, description, and accessible role guidance.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: ["AlertAction", "AlertDescription", "AlertTitle"],
		particlePriority: "mvp",
		status: "stable",
	},
	AlertDialog: {
		category: "Overlays & Popups",
		description: "A dialog that requires user response to proceed.",
		hasLocalPrimitiveRef: true,
		name: "AlertDialog",
		particles: 2,
		slug: "alert-dialog",
		title: "Alert Dialog",
		firstImplementationPass:
			"Map COSS Alert Dialog sections onto Bits UI primitives and make overlay interaction dismiss the popup consistently with the other modal components.",
		primitive: "AlertDialog",
		tier: "direct primitive",
		foundation: "bits",
		parts: [
			"AlertDialogAction",
			"AlertDialogCancel",
			"AlertDialogDescription",
			"AlertDialogFooter",
			"AlertDialogHeader",
			"AlertDialogPopup",
			"AlertDialogTitle",
			"AlertDialogTrigger",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Autocomplete: {
		category: "Selection & Input",
		description: "An input that suggests options as you type.",
		hasLocalPrimitiveRef: true,
		name: "Autocomplete",
		particles: 15,
		slug: "autocomplete",
		title: "Autocomplete",
		firstImplementationPass:
			"Build an autocomplete wrapper around Bits UI Combobox with input-first filtering, item rendering, empty state, grouped options, and form field composition.",
		primitive: "Combobox",
		tier: "compound primitive",
		foundation: "compound",
		parts: [
			"AutocompleteCollection",
			"AutocompleteEmpty",
			"AutocompleteGroup",
			"AutocompleteGroupLabel",
			"AutocompleteInput",
			"AutocompleteItem",
			"AutocompleteList",
			"AutocompletePopup",
			"AutocompleteSeparator",
			"AutocompleteStatus",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Avatar: {
		category: "Content & Display",
		description: "A visual representation of a user or entity.",
		hasLocalPrimitiveRef: true,
		name: "Avatar",
		particles: 14,
		slug: "avatar",
		title: "Avatar",
		firstImplementationPass:
			"Wrap Bits UI Avatar image/fallback parts and add COSS sizing, grouping, stacked avatar, status, and image fallback patterns.",
		primitive: "Avatar",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["AvatarFallback", "AvatarImage"],
		particlePriority: "mvp",
		status: "stable",
	},
	Badge: {
		category: "Content & Display",
		description: "A small status indicator or label component.",
		hasLocalPrimitiveRef: true,
		name: "Badge",
		particles: 20,
		slug: "badge",
		title: "Badge",
		firstImplementationPass:
			"Implement span/a/button-compatible badge variants with semantic color tokens, compact sizing, icon slots, and removable badge examples.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Breadcrumb: {
		category: "Layout & Navigation",
		description: "Displays the path to the current resource using a hierarchy of links.",
		hasLocalPrimitiveRef: true,
		name: "Breadcrumb",
		particles: 7,
		slug: "breadcrumb",
		title: "Breadcrumb",
		firstImplementationPass:
			"Use nav/ol/li markup with separators, ellipsis, current page semantics, truncation behavior, and optional menu-backed overflow.",
		primitive: "native nav",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Button: {
		category: "Actions",
		description: "A button or a component that looks like a button.",
		hasLocalPrimitiveRef: true,
		name: "Button",
		particles: 40,
		slug: "button",
		title: "Button",
		firstImplementationPass:
			"Define Button with explicit variant and size maps; support native button and link rendering, icon sizes, loading state, and button-group data styling.",
		primitive: "native button/link",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Calendar: {
		category: "Selection & Input",
		description: "A date picker for selecting single dates, ranges, or multiple dates.",
		hasLocalPrimitiveRef: true,
		name: "Calendar",
		particles: 24,
		slug: "calendar",
		title: "Calendar",
		firstImplementationPass:
			"Wrap Bits UI Calendar and RangeCalendar with COSS month grid styling, navigation controls, range/multiple modes, disabled dates, and locale-aware examples.",
		primitive: "Calendar / RangeCalendar",
		tier: "direct primitive",
		foundation: "bits",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Card: {
		category: "Content & Display",
		description: "A content container for grouping related information.",
		hasLocalPrimitiveRef: true,
		name: "Card",
		particles: 11,
		slug: "card",
		title: "Card",
		firstImplementationPass:
			"Create Card root/header/title/description/content/footer sections with data-slot styling and dense product UI examples.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: ["CardDescription", "CardFooter", "CardHeader", "CardPanel", "CardTitle"],
		particlePriority: "mvp",
		status: "stable",
	},
	Checkbox: {
		category: "Toggle & Choice",
		description: "A binary toggle input for selecting one or multiple options.",
		hasLocalPrimitiveRef: true,
		name: "Checkbox",
		particles: 5,
		slug: "checkbox",
		title: "Checkbox",
		firstImplementationPass:
			"Wrap Bits UI Checkbox root/indicator, add icon rendering, invalid/disabled states, Field integration, and row/card checkbox particle patterns.",
		primitive: "Checkbox",
		tier: "direct primitive",
		foundation: "bits",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	CheckboxGroup: {
		category: "Toggle & Choice",
		description: "A collection of related checkboxes with group-level control.",
		hasLocalPrimitiveRef: true,
		name: "CheckboxGroup",
		particles: 5,
		slug: "checkbox-group",
		title: "Checkbox Group",
		firstImplementationPass:
			"Compose Checkbox with group-level value management, Fieldset semantics, validation messages, and horizontal/vertical option layouts.",
		primitive: "Checkbox + custom group",
		tier: "compound primitive",
		foundation: "custom",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Collapsible: {
		category: "Layout & Navigation",
		description: "A component that toggles visibility of content sections.",
		hasLocalPrimitiveRef: true,
		name: "Collapsible",
		particles: 1,
		slug: "collapsible",
		title: "Collapsible",
		firstImplementationPass:
			"Wrap Bits UI Collapsible with trigger/content exports, animation data attributes, and simple disclosure examples.",
		primitive: "Collapsible",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["CollapsibleContent", "CollapsibleTrigger"],
		particlePriority: "mvp",
		status: "stable",
	},
	Combobox: {
		category: "Selection & Input",
		description: "An input combined with a list of predefined items to select.",
		hasLocalPrimitiveRef: true,
		name: "Combobox",
		particles: 18,
		slug: "combobox",
		title: "Combobox",
		firstImplementationPass:
			"Wrap Bits UI Combobox with trigger/input/content/item exports, object value handling, async examples, multi-select patterns, and Field integration.",
		primitive: "Combobox",
		tier: "direct primitive",
		foundation: "bits",
		parts: [
			"ComboboxClear",
			"ComboboxCollection",
			"ComboboxEmpty",
			"ComboboxGroup",
			"ComboboxGroupLabel",
			"ComboboxInput",
			"ComboboxItem",
			"ComboboxList",
			"ComboboxPopup",
			"ComboboxSeparator",
			"ComboboxTrigger",
			"ComboboxValue",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Command: {
		category: "Overlays & Popups",
		description:
			"A command palette component built with Dialog and Autocomplete for searching and executing commands.",
		hasLocalPrimitiveRef: true,
		name: "Command",
		particles: 2,
		slug: "command",
		title: "Command",
		firstImplementationPass:
			"Compose Bits UI Command with Dialog for palette use, define groups/items/shortcuts, and keep keyboard navigation and filtering behavior native.",
		primitive: "Command + Dialog",
		tier: "compound primitive",
		foundation: "compound",
		parts: [
			"CommandCollection",
			"CommandDialog",
			"CommandDialogPopup",
			"CommandDialogTrigger",
			"CommandEmpty",
			"CommandFooter",
			"CommandGroup",
			"CommandGroupLabel",
			"CommandInput",
			"CommandItem",
			"CommandList",
			"CommandPanel",
			"CommandSeparator",
			"CommandShortcut",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	DatePicker: {
		category: "Selection & Input",
		description:
			"A date selection component, often combined with a calendar in a popover or input.",
		hasLocalPrimitiveRef: false,
		name: "DatePicker",
		particles: 9,
		slug: "date-picker",
		title: "Date Picker",
		firstImplementationPass:
			"Prefer Bits UI DatePicker where it matches COSS; otherwise compose Popover, Button, and Calendar with formatter, range, and form examples.",
		primitive: "DatePicker / DateRangePicker",
		tier: "compound primitive",
		foundation: "compound",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Dialog: {
		category: "Overlays & Popups",
		description: "A modal overlay for displaying content that requires user interaction.",
		hasLocalPrimitiveRef: true,
		name: "Dialog",
		particles: 6,
		slug: "dialog",
		title: "Dialog",
		firstImplementationPass:
			"Wrap Bits UI Dialog root, trigger, portal, overlay, content, close, title, and description; add COSS header, panel, footer, and scroll behavior.",
		primitive: "Dialog",
		tier: "direct primitive",
		foundation: "bits",
		parts: [
			"DialogClose",
			"DialogDescription",
			"DialogFooter",
			"DialogHeader",
			"DialogPanel",
			"DialogPopup",
			"DialogTitle",
			"DialogTrigger",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Empty: {
		category: "Content & Display",
		description: "A container for displaying empty state information.",
		hasLocalPrimitiveRef: true,
		name: "Empty",
		particles: 1,
		slug: "empty",
		title: "Empty",
		firstImplementationPass:
			"Build Empty root/icon/title/description/actions sections for product empty states with compact and illustrated variants.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: ["EmptyContent", "EmptyDescription", "EmptyHeader", "EmptyMedia", "EmptyTitle"],
		particlePriority: "mvp",
		status: "stable",
	},
	Field: {
		category: "Forms & Validation",
		description: "A wrapper component for form inputs with labels and validation.",
		hasLocalPrimitiveRef: true,
		name: "Field",
		particles: 18,
		slug: "field",
		title: "Field",
		firstImplementationPass:
			"Create Field root, label, description, error, and control conventions with aria-describedby wiring and invalid/required data attributes.",
		primitive: "Label + native semantics",
		tier: "compound primitive",
		foundation: "compound",
		parts: ["FieldDescription", "FieldError", "FieldLabel", "FieldValidity"],
		particlePriority: "mvp",
		status: "stable",
	},
	Fieldset: {
		category: "Forms & Validation",
		description: "A group of related form fields with a common label.",
		hasLocalPrimitiveRef: true,
		name: "Fieldset",
		particles: 1,
		slug: "fieldset",
		title: "Fieldset",
		firstImplementationPass:
			"Wrap fieldset/legend semantics with Field-compatible description and error slots for grouped controls.",
		primitive: "native fieldset",
		tier: "presentational",
		foundation: "native",
		parts: ["FieldsetLegend"],
		particlePriority: "mvp",
		status: "stable",
	},
	Form: {
		category: "Forms & Validation",
		description: "A complete form implementation with validation and submission handling.",
		hasLocalPrimitiveRef: true,
		name: "Form",
		particles: 2,
		slug: "form",
		title: "Form",
		firstImplementationPass:
			"Keep framework-agnostic form sections first; add SvelteKit enhance examples and optional validation adapters without hard-coding a form library.",
		primitive: "native form",
		tier: "integration layer",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Frame: {
		category: "Content & Display",
		description: "A container component for displaying content in a frame.",
		hasLocalPrimitiveRef: true,
		name: "Frame",
		particles: 4,
		slug: "frame",
		title: "Frame",
		firstImplementationPass:
			"Implement framed preview/media containers with aspect constraints, subtle borders, loading/error slots, and code-preview use cases.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: ["FrameDescription", "FrameFooter", "FrameHeader", "FramePanel", "FrameTitle"],
		particlePriority: "mvp",
		status: "stable",
	},
	Group: {
		category: "Content & Display",
		description: "A container component for grouping related content with consistent styling.",
		hasLocalPrimitiveRef: true,
		name: "Group",
		particles: 22,
		slug: "group",
		title: "Group",
		firstImplementationPass:
			"Create grouping primitives for attached controls, segmented surfaces, and density-consistent product layouts using data-slot selectors.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: ["GroupSeparator"],
		particlePriority: "mvp",
		status: "stable",
	},
	Input: {
		category: "Selection & Input",
		description: "A native input element.",
		hasLocalPrimitiveRef: true,
		name: "Input",
		particles: 19,
		slug: "input",
		title: "Input",
		firstImplementationPass:
			"Implement styled input with sizing, invalid/disabled states, file input handling, leading/trailing icon compatibility, and Field integration.",
		primitive: "native input",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	InputGroup: {
		category: "Selection & Input",
		description:
			"A flexible component for grouping inputs with addons, buttons, and other elements.",
		hasLocalPrimitiveRef: true,
		name: "InputGroup",
		particles: 28,
		slug: "input-group",
		title: "Input Group",
		firstImplementationPass:
			"Build strict-order addons, controls, buttons, textareas, and prefix/suffix composition with layout invariants documented in examples.",
		primitive: "native markup",
		tier: "compound primitive",
		foundation: "compound",
		parts: ["InputGroupAddon", "InputGroupInput", "InputGroupText", "InputGroupTextarea"],
		particlePriority: "mvp",
		status: "stable",
	},
	Kbd: {
		category: "Content & Display",
		description: "A component for displaying keyboard keys and shortcuts.",
		hasLocalPrimitiveRef: true,
		name: "Kbd",
		particles: 1,
		slug: "kbd",
		title: "Kbd",
		firstImplementationPass:
			"Style keyboard shortcut tokens with compact sizing, command-key normalization examples, and inline/list usage.",
		primitive: "native kbd",
		tier: "presentational",
		foundation: "native",
		parts: ["KbdGroup"],
		particlePriority: "mvp",
		status: "stable",
	},
	Label: {
		category: "Forms & Validation",
		description: "Renders an accessible label associated with controls.",
		hasLocalPrimitiveRef: true,
		name: "Label",
		particles: 0,
		slug: "label",
		title: "Label",
		firstImplementationPass:
			"Wrap Bits UI Label with consistent typography, disabled state propagation, and Field-compatible usage.",
		primitive: "Label",
		tier: "direct primitive",
		foundation: "bits",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Menu: {
		category: "Overlays & Popups",
		description: "A list of actions or options revealed on demand.",
		hasLocalPrimitiveRef: true,
		name: "Menu",
		particles: 9,
		slug: "menu",
		title: "Menu",
		firstImplementationPass:
			"Map COSS Menu exports to Bits UI menu primitives, covering trigger, popup, item, checkbox/radio items, submenus, separators, labels, and shortcuts.",
		primitive: "DropdownMenu / ContextMenu / Menu",
		tier: "compound primitive",
		foundation: "compound",
		parts: [
			"MenuCheckboxItem",
			"MenuGroup",
			"MenuGroupLabel",
			"MenuItem",
			"MenuPopup",
			"MenuRadioGroup",
			"MenuRadioItem",
			"MenuSeparator",
			"MenuShortcut",
			"MenuSub",
			"MenuSubPopup",
			"MenuSubTrigger",
			"MenuTrigger",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	ContextMenu: {
		category: "Overlays & Popups",
		description: "A menu of contextual actions opened from a pointer or keyboard target.",
		hasLocalPrimitiveRef: true,
		name: "ContextMenu",
		particles: 8,
		slug: "context-menu",
		title: "Context Menu",
		firstImplementationPass:
			"Wrap Bits UI ContextMenu with pointer and keyboard triggers, action and link items, checkbox and radio controls, nested submenus, labels, separators, and shortcuts.",
		primitive: "ContextMenu",
		tier: "direct primitive",
		foundation: "bits",
		parts: [
			"ContextMenuCheckboxItem",
			"ContextMenuGroup",
			"ContextMenuGroupLabel",
			"ContextMenuItem",
			"ContextMenuLinkItem",
			"ContextMenuPopup",
			"ContextMenuRadioGroup",
			"ContextMenuRadioItem",
			"ContextMenuSeparator",
			"ContextMenuShortcut",
			"ContextMenuSub",
			"ContextMenuSubPopup",
			"ContextMenuSubTrigger",
			"ContextMenuTrigger",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Meter: {
		category: "Feedback & Status",
		description: "A visual representation of a value within a known range.",
		hasLocalPrimitiveRef: true,
		name: "Meter",
		particles: 4,
		slug: "meter",
		title: "Meter",
		firstImplementationPass:
			"Wrap Bits UI Meter with value/label exports, thresholds, color states, and compact status examples.",
		primitive: "Meter",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["MeterIndicator", "MeterLabel", "MeterTrack", "MeterValue"],
		particlePriority: "mvp",
		status: "stable",
	},
	OTPField: {
		category: "Selection & Input",
		description: "A segmented input for one-time passwords and verification codes.",
		hasLocalPrimitiveRef: true,
		name: "OTPField",
		particles: 9,
		slug: "otp-field",
		title: "OTP Field",
		firstImplementationPass:
			"Wrap Bits UI PinInput as OTPField with one input per character, separators, grouped layouts, paste handling, and verification form examples.",
		primitive: "PinInput",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["OTPFieldCell", "OTPFieldInput"],
		particlePriority: "mvp",
		status: "stable",
	},
	Pagination: {
		category: "Layout & Navigation",
		description: "A pagination with page navigation, next and previous links.",
		hasLocalPrimitiveRef: true,
		name: "Pagination",
		particles: 3,
		slug: "pagination",
		title: "Pagination",
		firstImplementationPass:
			"Wrap Bits UI Pagination with previous/next/items/ellipsis exports and routing-friendly link rendering for SvelteKit.",
		primitive: "Pagination",
		tier: "direct primitive",
		foundation: "bits",
		parts: [
			"PaginationContent",
			"PaginationEllipsis",
			"PaginationItem",
			"PaginationLink",
			"PaginationNext",
			"PaginationNextButton",
			"PaginationPage",
			"PaginationPrevious",
			"PaginationPrevButton",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Popover: {
		category: "Overlays & Popups",
		description: "An accessible popup anchored to a button.",
		hasLocalPrimitiveRef: true,
		name: "Popover",
		particles: 3,
		slug: "popover",
		title: "Popover",
		firstImplementationPass:
			"Wrap Bits UI Popover with trigger/content/arrow exports, portal forwarding, collision options, and form/filter examples.",
		primitive: "Popover",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["PopoverClose", "PopoverDescription", "PopoverPopup", "PopoverTitle", "PopoverTrigger"],
		particlePriority: "mvp",
		status: "stable",
	},
	PreviewCard: {
		category: "Overlays & Popups",
		description: "A rich preview component for displaying linked content.",
		hasLocalPrimitiveRef: true,
		name: "PreviewCard",
		particles: 1,
		slug: "preview-card",
		title: "Preview Card",
		firstImplementationPass:
			"Wrap Bits UI LinkPreview with trigger/content exports and rich preview card styling for links, users, and resources.",
		primitive: "LinkPreview",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["PreviewCardPopup", "PreviewCardTrigger"],
		particlePriority: "mvp",
		status: "stable",
	},
	Progress: {
		category: "Feedback & Status",
		description: "A visual indicator showing the completion status of a task.",
		hasLocalPrimitiveRef: true,
		name: "Progress",
		particles: 3,
		slug: "progress",
		title: "Progress",
		firstImplementationPass:
			"Wrap Bits UI Progress with determinate/indeterminate styling, labels, stacked examples, and semantic value text.",
		primitive: "Progress",
		tier: "direct primitive",
		foundation: "bits",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	RadioGroup: {
		category: "Toggle & Choice",
		description: "A set of mutually exclusive options presented as radio buttons.",
		hasLocalPrimitiveRef: true,
		name: "RadioGroup",
		particles: 6,
		slug: "radio-group",
		title: "Radio Group",
		firstImplementationPass:
			"Wrap Bits UI RadioGroup with item/indicator exports, card options, Fieldset composition, and keyboard testing.",
		primitive: "RadioGroup",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["RadioGroupItem"],
		particlePriority: "mvp",
		status: "stable",
	},
	ScrollArea: {
		category: "Layout & Navigation",
		description: "A container with custom scrollbars for overflow content.",
		hasLocalPrimitiveRef: true,
		name: "ScrollArea",
		particles: 5,
		slug: "scroll-area",
		title: "Scroll Area",
		firstImplementationPass:
			"Wrap Bits UI ScrollArea with viewport/scrollbar/thumb exports and table, menu, and long-content examples.",
		primitive: "ScrollArea",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["ScrollAreaCorner", "ScrollAreaScrollbar", "ScrollAreaThumb", "ScrollAreaViewport"],
		particlePriority: "mvp",
		status: "stable",
	},
	Select: {
		category: "Selection & Input",
		description: "A common form component for choosing a predefined value in a dropdown menu.",
		hasLocalPrimitiveRef: true,
		name: "Select",
		particles: 23,
		slug: "select",
		title: "Select",
		firstImplementationPass:
			"Map COSS items-first Select patterns to Bits UI Select with trigger/value/content/item/group/label exports, object values, multiple mode, and form serialization.",
		primitive: "Select",
		tier: "direct primitive",
		foundation: "bits",
		parts: [
			"SelectGroup",
			"SelectGroupLabel",
			"SelectItem",
			"SelectPopup",
			"SelectScrollDownButton",
			"SelectScrollUpButton",
			"SelectTrigger",
			"SelectValue",
			"SelectViewport",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Separator: {
		category: "Content & Display",
		description: "A visual divider for separating content sections.",
		hasLocalPrimitiveRef: true,
		name: "Separator",
		particles: 1,
		slug: "separator",
		title: "Separator",
		firstImplementationPass:
			"Wrap Bits UI Separator with orientation variants, decorative semantics, and menu/card separation examples.",
		primitive: "Separator",
		tier: "direct primitive",
		foundation: "bits",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Sheet: {
		category: "Overlays & Popups",
		description: "A flyout that opens from the side of the screen, based on the dialog component.",
		hasLocalPrimitiveRef: true,
		name: "Sheet",
		particles: 3,
		slug: "sheet",
		title: "Sheet",
		firstImplementationPass:
			"Compose Dialog with side placement classes, overlay/content exports, responsive widths, and close behavior matching COSS Sheet.",
		primitive: "Dialog",
		tier: "compound primitive",
		foundation: "compound",
		parts: [
			"SheetClose",
			"SheetContent",
			"SheetDescription",
			"SheetFooter",
			"SheetHeader",
			"SheetPanel",
			"SheetPopup",
			"SheetTitle",
			"SheetTrigger",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Skeleton: {
		category: "Feedback & Status",
		description: "A placeholder for loading content.",
		hasLocalPrimitiveRef: true,
		name: "Skeleton",
		particles: 2,
		slug: "skeleton",
		title: "Skeleton",
		firstImplementationPass:
			"Implement animated placeholder blocks with shape variants, reduced-motion handling, and page/card/table skeleton examples.",
		primitive: "native markup",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Slider: {
		category: "Selection & Input",
		description: "A draggable control for selecting values from a continuous range.",
		hasLocalPrimitiveRef: true,
		name: "Slider",
		particles: 23,
		slug: "slider",
		title: "Slider",
		firstImplementationPass:
			"Wrap Bits UI Slider with thumb/range/track exports, scalar and range modes, value labels, marks, and Field integration.",
		primitive: "Slider",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["SliderRange", "SliderThumb", "SliderThumbLabel", "SliderTick", "SliderTickLabel"],
		particlePriority: "mvp",
		status: "stable",
	},
	Spinner: {
		category: "Feedback & Status",
		description: "An indicator that can be used to show a loading state.",
		hasLocalPrimitiveRef: true,
		name: "Spinner",
		particles: 1,
		slug: "spinner",
		title: "Spinner",
		firstImplementationPass:
			"Create accessible loading indicator variants with size, label, reduced-motion, and button/input loading composition examples.",
		primitive: "native SVG/CSS",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Switch: {
		category: "Toggle & Choice",
		description: "A toggle control for binary on/off states.",
		hasLocalPrimitiveRef: true,
		name: "Switch",
		particles: 6,
		slug: "switch",
		title: "Switch",
		firstImplementationPass:
			"Wrap Bits UI Switch with thumb styling, labels, Field composition, and settings-row particle patterns.",
		primitive: "Switch",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["SwitchThumb"],
		particlePriority: "mvp",
		status: "stable",
	},
	Table: {
		category: "Content & Display",
		description: "A structured data display component with rows and columns.",
		hasLocalPrimitiveRef: true,
		name: "Table",
		particles: 8,
		slug: "table",
		title: "Table",
		firstImplementationPass:
			"Implement table section components with responsive overflow wrapper, density variants, numeric alignment, empty rows, and toolbar integration.",
		primitive: "native table",
		tier: "presentational",
		foundation: "native",
		parts: [
			"TableBody",
			"TableCaption",
			"TableCell",
			"TableFooter",
			"TableHead",
			"TableHeader",
			"TableRow",
		],
		particlePriority: "mvp",
		status: "stable",
	},
	Tabs: {
		category: "Layout & Navigation",
		description: "A component for toggling between related panels on the same page.",
		hasLocalPrimitiveRef: true,
		name: "Tabs",
		particles: 13,
		slug: "tabs",
		title: "Tabs",
		firstImplementationPass:
			"Wrap Bits UI Tabs list/trigger/content with variant styling and orientation support, and mirror COSS's default 200ms shared active indicator by measuring the selected Svelte trigger.",
		primitive: "Tabs",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["TabsContent", "TabsList", "TabsTrigger"],
		particlePriority: "mvp",
		status: "stable",
	},
	Textarea: {
		category: "Selection & Input",
		description: "A multi-line text input for longer content.",
		hasLocalPrimitiveRef: true,
		name: "Textarea",
		particles: 15,
		slug: "textarea",
		title: "Textarea",
		firstImplementationPass:
			"Implement styled textarea with autosize guidance, invalid/disabled states, InputGroup compatibility, and Field integration.",
		primitive: "native textarea",
		tier: "presentational",
		foundation: "native",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	Toggle: {
		category: "Toggle & Choice",
		description: "A button that switches between two states.",
		hasLocalPrimitiveRef: true,
		name: "Toggle",
		particles: 8,
		slug: "toggle",
		title: "Toggle",
		firstImplementationPass:
			"Wrap Bits UI Toggle with button variants, pressed state styling, icon-only accessibility, and toolbar examples.",
		primitive: "Toggle",
		tier: "direct primitive",
		foundation: "bits",
		parts: [],
		particlePriority: "mvp",
		status: "stable",
	},
	ToggleGroup: {
		category: "Toggle & Choice",
		description: "A group of toggle buttons where one or multiple can be selected.",
		hasLocalPrimitiveRef: true,
		name: "ToggleGroup",
		particles: 9,
		slug: "toggle-group",
		title: "Toggle Group",
		firstImplementationPass:
			"Wrap Bits UI ToggleGroup with single/multiple modes, roving focus, item variants, and segmented-control examples.",
		primitive: "ToggleGroup",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["ToggleGroupItem"],
		particlePriority: "mvp",
		status: "stable",
	},
	Toolbar: {
		category: "Layout & Navigation",
		description: "A container for grouping related actions or controls.",
		hasLocalPrimitiveRef: true,
		name: "Toolbar",
		particles: 1,
		slug: "toolbar",
		title: "Toolbar",
		firstImplementationPass:
			"Wrap Bits UI Toolbar with group/separator/button composition, roving focus, and editor/action-bar examples.",
		primitive: "Toolbar",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["ToolbarButton", "ToolbarGroup", "ToolbarGroupItem", "ToolbarLink", "ToolbarSeparator"],
		particlePriority: "mvp",
		status: "stable",
	},
	Tooltip: {
		category: "Overlays & Popups",
		description: "A small overlay that provides contextual information on hover or focus.",
		hasLocalPrimitiveRef: true,
		name: "Tooltip",
		particles: 4,
		slug: "tooltip",
		title: "Tooltip",
		firstImplementationPass:
			"Wrap Bits UI Tooltip provider/root/trigger/content/arrow with delay, side/align options, and icon-button guidance.",
		primitive: "Tooltip",
		tier: "direct primitive",
		foundation: "bits",
		parts: ["TooltipPopup", "TooltipProvider", "TooltipTrigger"],
		particlePriority: "mvp",
		status: "stable",
	},
	Drawer: {
		category: "Overlays & Popups",
		description:
			"A panel that slides in from the edge of the screen with swipe gestures, snap points, and nested drawer support.",
		hasLocalPrimitiveRef: true,
		name: "Drawer",
		particles: 14,
		slug: "drawer",
		title: "Drawer",
		firstImplementationPass:
			"Experimental in 0.1.0: dialog-style opening, closing, focus, and edge placement are available; swipe gestures, snap points, nested drawers, and responsive dialog switching are not yet supported.",
		primitive: "Dialog accessibility shell + custom motion",
		tier: "custom compound",
		foundation: "custom",
		parts: [
			"DrawerClose",
			"DrawerContent",
			"DrawerCreateHandle",
			"DrawerDescription",
			"DrawerFooter",
			"DrawerHeader",
			"DrawerPanel",
			"DrawerPopup",
			"DrawerTitle",
			"DrawerTrigger",
		],
		particlePriority: "later",
		status: "experimental",
	},
	Sidebar: {
		category: "Layout & Navigation",
		description: "A collapsible side panel for navigation and secondary content.",
		hasLocalPrimitiveRef: true,
		name: "Sidebar",
		particles: 0,
		slug: "sidebar",
		title: "Sidebar",
		firstImplementationPass:
			"Experimental in 0.1.0: the compound sidebar and controlled collapsed state are available; responsive drawer behavior and persisted layout state are not yet complete.",
		primitive: "Collapsible + native navigation",
		tier: "compound primitive",
		foundation: "compound",
		parts: [
			"SidebarContent",
			"SidebarFooter",
			"SidebarGroup",
			"SidebarGroupAction",
			"SidebarGroupContent",
			"SidebarGroupLabel",
			"SidebarHeader",
			"SidebarInput",
			"SidebarInset",
			"SidebarMenu",
			"SidebarMenuAction",
			"SidebarMenuBadge",
			"SidebarMenuButton",
			"SidebarMenuItem",
			"SidebarMenuSkeleton",
			"SidebarMenuSub",
			"SidebarMenuSubButton",
			"SidebarMenuSubItem",
			"SidebarProvider",
			"SidebarRail",
			"SidebarSeparator",
			"SidebarTrigger",
		],
		particlePriority: "later",
		status: "experimental",
	},
	Toast: {
		category: "Feedback & Status",
		description: "A temporary notification message that appears and disappears automatically.",
		hasLocalPrimitiveRef: true,
		name: "Toast",
		particles: 13,
		slug: "toast",
		title: "Toast",
		firstImplementationPass:
			"Experimental in 0.1.0: the provider, timed notifications, and manual dismissal are available; swipe dismissal, promise helpers, and advanced update controls are not yet supported.",
		primitive: "custom store + portal",
		tier: "custom compound",
		foundation: "custom",
		parts: ["ToastProvider"],
		particlePriority: "later",
		status: "experimental",
	},
	NumberField: {
		category: "Selection & Input",
		description: "A specialized input for numeric values with increment/decrement controls.",
		hasLocalPrimitiveRef: true,
		name: "NumberField",
		particles: 11,
		slug: "number-field",
		title: "Number Field",
		firstImplementationPass:
			"Implement an accessible spinbutton-style input with increment/decrement controls, min/max/step, formatting hooks, and Field integration.",
		primitive: "custom spinbutton",
		tier: "custom primitive",
		foundation: "custom",
		parts: [
			"NumberFieldDecrement",
			"NumberFieldGroup",
			"NumberFieldIncrement",
			"NumberFieldInput",
			"NumberFieldScrubArea",
		],
		particlePriority: "mvp",
		status: "stable",
	},
});

const metadataEntries = Object.entries(componentMetadata);

export const componentStatus = Object.freeze(
	Object.fromEntries(metadataEntries.map(([name, metadata]) => [name, metadata.status]))
);

export const componentParts = Object.freeze(
	Object.fromEntries(metadataEntries.map(([name, metadata]) => [name, metadata.parts]))
);

/** @param {"stable" | "experimental" | "deferred"} status */
const componentsByStatus = (status) =>
	metadataEntries.filter(([, metadata]) => metadata.status === status).map(([name]) => name);

export const stableComponents = Object.freeze(componentsByStatus("stable"));
export const experimentalComponents = Object.freeze(componentsByStatus("experimental"));
export const deferredComponents = Object.freeze(componentsByStatus("deferred"));
